'use strict';
/**
 * Writes assets/js/runtime-config.js from environment variables (Vercel build).
 * Set PUBLIC_API_BASE to your backend URL, e.g. https://vcg-backend.vercel.app
 */
const fs = require('fs');
const path = require('path');

const base = (process.env.PUBLIC_API_BASE || process.env.API_BASE || '').trim().replace(/\/$/, '');
const ga = (process.env.PUBLIC_GA_ID || '').trim();
const sentry = (process.env.PUBLIC_SENTRY_DSN || '').trim();

const out = `/* Generated by npm run build — do not edit */
window.__API_BASE__ = ${JSON.stringify(base)};
window.__PUBLIC_GA_ID__ = ${JSON.stringify(ga)};
window.__PUBLIC_SENTRY_DSN__ = ${JSON.stringify(sentry)};
`;

const target = path.join(__dirname, '..', 'assets', 'js', 'runtime-config.js');
fs.writeFileSync(target, out, 'utf8');
console.log('[inject-config] wrote', target, 'API_BASE=', base || '(empty)');
